# run: conda env create --file environment.yml
name: attention_tsp
channels:
- pytorch
dependencies:
- python=3.8
- anaconda=2024
- tqdm=4.65
- pytorch=2.2
- torchvision=0.17
- cuda91=1.0
- pip=23.3
- pip:
  - tensorboard_logger=0.1
